title: Jess Strzempko
logo: /assets/img/profile.png
description: Aspiring geospatial professional and current M.S. GIS candidate at Clark University with a background in environmental science, mathematics, and land change modeling and a passion for understanding human-environment relations. Experience with, and curiosity for, a variety of software packages (ArcGIS products, QGIS, TerrSet, GeoDa) and programming languages (R, Python, JavaScript).
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
