title: Jess Strzempko
logo: /assets/img/profile.png
description: Aspiring Geospatial Professional & Current M.S. GIS Candidate at Clark University
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
